### ISSUE TITLE
Strange auto-selecting of search results

### ISSUE THREAD

**Issue by wisniewskit** [wisniewskit/google-search-fixer#23]
As reported in https://github.com/mozilla-mobile/fenix/issues/23058, it appears after issuing a search in the URL bar, the search results page will automatically act as though the user has tapped on a random (?) search result. I'm currently unable to reproduce this on my phone, so I'm hoping to find out if other addons might also be active, or even an A/B test Google might be running (since I've only received two reports of this over the past week, and I would expect more if it was consistently happening).

**Comment by paleparanoid** [comment]
I'm here. 
Do you have more questions for me?
Now I moved to Chrome Canary, because I really need Google shown in normal interface.
I think it's Firefox's problem, not extension's. Day ago I manually changed User-Agent in about:config to latest Chrome. This bug repeats again.
I can download Firefox Nightly again, change user-agent again and show that this bug repeats.

**Comment by paleparanoid** [comment]
I made it.
You can see.

https://user-images.githubusercontent.com/86261854/148360592-0311efa4-9343-43a5-bb83-7f451ca394ac.mp4

**Comment by paleparanoid** [comment]
Maybe I found the reason.
I have Adguard App (app that blocks ads via VPN and also filters HTTPS using User Credentials (User CA))
After disabling Protection nothing redirected me
Video is here, because GitHub doesn't accept it, maybe because of size: https://drive.google.com/file/d/143qoRT3QzvASdvkL8_oTkSS8bOC0jN_D/view?usp=drivesdk

I haven't found what's wrong in Adguard, because in Chrome with the same settings everything works fine.
I thought that User-Agent change feature does something like this but After disabling it nothing changed - endless redirects
![Screenshot_20220106-162056](https://user-images.githubusercontent.com/86261854/148389079-9f6fa391-330d-4717-a984-443162baf43a.png)

Also I can show what adguard blocks on Google
![Screenshot_20220106-161949](https://user-images.githubusercontent.com/86261854/148389150-2eb5f1b0-0e11-486e-a343-6ad41e654130.png)

I have many thoughts about this
Maybe it's because Fanboy Anti Third-Party Fonts filter (It blocked fonts.gstatic.com there)
Maybe because of disabe AMP script?
![Screenshot_20220106-162334](https://user-images.githubusercontent.com/86261854/148389426-d1ff0676-bf0a-474e-b47a-5966c9b7a0af.png)

Even if I find the reason from some of the things above
I still have a question
Why does it happens only on Firefox?
In chrome with the same settings of Adguard everything is nice

**Comment by wisniewskit** [comment]
Thanks so much for the additional info!

I'm afraid that this may not be very easy to figure out; my first suspicion was that it isn't really caused by Firefox or this add-on per se, but rather that there is something about Chrome that their website is relying on, like a web API that doesn't work exactly the same way as in Firefox, or some information Chrome presents which Firefox does not (which they would feel free to rely on, since the user-agent is a Chrome-like one).

But since this is related to AdGuard, I'm not sure what that app might do which influences this. All this addon really does is change the user-agent string and disable service workers on Google Search. I think I might have to reach out to them (when time permits) to get some more insight on why it's a factor.

**Comment by paleparanoid** [comment]
I also think that it isn't Firefox's, Google Search Fixer's or Adguard's fault
This is most likely it's due to Google APIs
However, without contacting Google we can't do anything else
It would be nice if they'll fix displaying of Google search in Firefox at the level of their systems.
I don't understand, why they rape the view of search only in Firefox mobile like this.

**Comment by wisniewskit** [comment]
I can't speak for Google, I can only say that I feel your pain, as I'm one of the folks who have been pushing them for years to deliver the same experience to all browsers that they deliver to their own (and not just on their search pages).

But I will do my best to find time to reproduce the problem and investigate it closer, now that I know AdGuard is involved. Perhaps I will be able to find a solid work-around, and hopefully soon.

**Comment by paleparanoid** [comment]
Okay, thanks.
I hope what this problem will be solved soon, because I don't want to deal with Chrome, it's laggy and slow relatively Firefox Nightly. 
I gave as much information as I could.

**Comment by paleparanoid** [comment]
Update: with new Adguard Nightly update sites don't open by themselves anymore
Everything is fine for now
It wasn't your extension's fault in my situation

**Comment by Rob--W** [comment]
@wisniewskit Can this issue be closed now?

**Comment by wisniewskit** [comment]
I think so.
